# MINTDuels - Made by MINTY
# https://github.com/MINTYdv
#
# Version 1.0.0
# Configuration File (config.yml)
#
# Plugin Permissions :
# - mintduels.command.duel - Access to all duels commands (/duel, /accept)